# Generated by Django 3.2.9 on 2021-11-30 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=125)),
                ('message', models.TextField(max_length=255)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
