# Generated by Django 3.2.9 on 2021-12-03 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_subscribe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=125)),
                ('password', models.CharField(max_length=125)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
