# Generated by Django 3.2.9 on 2021-12-03 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('username', models.CharField(max_length=125)),
                ('password', models.CharField(max_length=125)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
