# Generated by Django 3.2.9 on 2021-11-24 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=125)),
                ('district', models.CharField(max_length=125)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='profile/images')),
                ('name', models.CharField(max_length=125)),
                ('profession', models.CharField(max_length=125)),
                ('age', models.CharField(max_length=125)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=125)),
                ('resume', models.FileField(upload_to='profile/documents')),
                ('description', models.TextField(max_length=255)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.address')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
