# Generated by Django 3.2.9 on 2021-11-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20211126_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=125)),
                ('course', models.CharField(max_length=125)),
                ('university', models.CharField(max_length=125)),
                ('description', models.TextField(max_length=125)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
