# Generated by Django 3.2.9 on 2021-11-30 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=125)),
                ('work', models.CharField(max_length=125)),
                ('company', models.CharField(max_length=125)),
                ('description', models.TextField(max_length=125)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
