# Generated by Django 3.2.9 on 2021-11-30 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('image', models.ImageField(upload_to='client/')),
                ('company', models.CharField(max_length=125)),
                ('description', models.TextField(max_length=125)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
