# Generated by Django 3.2.9 on 2021-11-30 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='district',
            new_name='permanent_district',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='state',
            new_name='permanent_state',
        ),
        migrations.AddField(
            model_name='address',
            name='current_disctrict',
            field=models.CharField(default=models.CharField(max_length=125), max_length=125),
        ),
        migrations.AddField(
            model_name='address',
            name='current_state',
            field=models.CharField(default=models.CharField(max_length=125), max_length=125),
        ),
    ]
