# Generated by Django 3.2.9 on 2021-11-30 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='service/')),
                ('title', models.CharField(max_length=125)),
                ('description', models.TextField(max_length=355)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
