# Generated by Django 3.2.9 on 2021-11-30 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_client'),
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.FileField(upload_to='project/thumb')),
                ('feature_image', models.ImageField(upload_to='project/feature_image')),
                ('title', models.CharField(max_length=125)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_satisfied', models.BooleanField(default=False)),
                ('category', models.CharField(max_length=125)),
                ('clients', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.client')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
